import type { Experiment } from "./types";

export default function ExperimentPanel({ experiment, selectRun, cancel }: { experiment: Experiment; selectRun: (id: string) => void; cancel: () => void }) {
  const summary = experiment.summary;
  const confidence = summary.confidence;
  const formatInterval = (interval: { lower: number | null; upper: number | null }) => interval.lower === null || interval.upper === null ? "Needs 2+ pairs" : `${Math.round(interval.lower * 100)}–${Math.round(interval.upper * 100)}%`;
  return <section className="experiment-panel">
    <div className="experiment-head"><div><p className="eyebrow">PAIRED EXPERIMENT · {experiment.seeds.length} SEEDS</p><h2>{experiment.candidate_policy_id} <span>vs</span> {experiment.baseline_policy_id}</h2></div><div className="experiment-actions">{experiment.status === "running" && <button onClick={cancel}>Cancel</button>}<a href={`/api/experiments/${experiment.id}/export?format=json`}>JSON</a><a href={`/api/experiments/${experiment.id}/export?format=csv`}>CSV</a><a href={`/api/experiments/${experiment.id}/export?format=junit`}>JUnit</a><strong className={`experiment-verdict ${experiment.verdict}`}>{experiment.verdict}</strong></div></div>
    <div className="experiment-summary"><div><small>Candidate pass</small><strong>{summary.candidate_pass_rate === null ? "—" : `${Math.round(summary.candidate_pass_rate * 100)}%`}</strong></div><div><small>Baseline pass</small><strong>{summary.baseline_pass_rate === null ? "—" : `${Math.round(summary.baseline_pass_rate * 100)}%`}</strong></div><div><small>Pass-rate delta</small><strong>{summary.pass_rate_delta === null ? "—" : `${summary.pass_rate_delta > 0 ? "+" : ""}${Math.round(summary.pass_rate_delta * 100)} pp`}</strong></div><div><small>Completed pairs</small><strong>{summary.completed_pairs}/{summary.total_pairs}</strong></div></div>
    {confidence && <div className={`confidence-strip ${confidence.sample_guidance}`}><div><small>95% candidate pass interval</small><strong>{formatInterval(confidence.candidate_pass_rate)}</strong></div><div><small>95% baseline pass interval</small><strong>{formatInterval(confidence.baseline_pass_rate)}</strong></div><p><b>{confidence.sample_guidance === "sufficient_for_regression_screen" ? "Regression sample" : "Development signal only"}</b> {confidence.sample_size}/{confidence.recommended_minimum_pairs} recommended paired runs.</p></div>}
    {experiment.gate_results.length > 0 && <div className="gate-strip">{experiment.gate_results.map(gate => <div className={gate.passed ? "gate-pass" : "gate-fail"} key={gate.id}><i>{gate.passed ? "PASS" : "FAIL"}</i><span>{gate.id.replaceAll("_", " ")}</span><small>{gate.actual.toFixed(2)} {gate.operator} {gate.limit}</small></div>)}</div>}
    <div className="seed-matrix"><div className="seed-head"><span>SEED</span><span>CANDIDATE</span><span>BASELINE</span><span>Δ COLLISIONS</span><span>FAILURE</span></div>{experiment.pairs.map(pair => <button key={pair.seed} onClick={() => selectRun(pair.candidate_run.id)}><strong>{pair.seed}</strong><span className={pair.candidate_run.verdict ?? "pending"}>{pair.candidate_run.verdict ?? pair.candidate_run.status}</span><span>{pair.baseline_run.verdict ?? pair.baseline_run.status}</span><span>{pair.metric_deltas.collisions === null ? "—" : `${pair.metric_deltas.collisions > 0 ? "+" : ""}${pair.metric_deltas.collisions}`}</span><small>{pair.failure_reasons.join(", ") || "—"}</small></button>)}</div>
  </section>;
}
